taloc_app:
    resource: "@TalocAppBundle/Controller/"
    type: annotation

taloc_user:
    resource: "@TalocUserBundle/Controller/"
    type: annotation

    
admin_login_check:
    path: /admin/login_check
    defaults: { _controller: TalocAppBundle:Backend:login_check }


