security:
    encoders:
        Taloc\UserBundle\Entity\User: plaintext
            #algorithm: bcrypt
            #cost: 12

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers: 
        front_provider:
            entity: { class: \Taloc\UserBundle\Entity\User }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:  ^/(?!admin)
            anonymous: ~
            form_login:
                provider: front_provider
                login_path: /login
                check_path: /login_check
                username_parameter: form[user_email]
                password_parameter: form[user_password]
                default_target_path:  /
            context: main
            logout:
                path:   /logout
                target: /login
            
        admin:
            pattern:  ^/admin
            anonymous: ~
            context: admin
        default:
            anonymous: ~    
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/check_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(?!admin), roles: ROLE_USER }
        
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        

