security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        #EntityBundle\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        #administrators:
           # entity: { class: EntityBundle:User, property: user_username }
        in_memory:
            memory:
                users:
                    admin:
                        password: 'admin'
                        roles: 'ROLE_ADMIN'    
            

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:  ^/(?!admin)
            anonymous: ~
            form_login:
                login_path: /login_form_front
                check_path: /login_check_front
            context: main
            
        admin:
            pattern:  ^/admin
            anonymous: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin/welcome
                # field names for the username and password fields
                username_parameter: user_username
                password_parameter: user_password
            context: admin
        
            
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(?!admin), roles: ROLE_ADMIN }
