security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        #EntityBundle\User:
            # algorithm:            plaintext
             #ignore_case:          false
        FOS\UserBundle\Model\UserInterface: sha512     

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers: 
        fos_userbundle:
            id: fos_user.user_provider.username    

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:  ^/(?!admin)
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            context: main
            logout:
                path:   /logout
                target: /login
            
        admin:
            pattern:  ^/admin
            anonymous: ~
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin/
            logout: 
                path:   /admin/logout
                target: /admin/login
            context: admin
        default:
            anonymous: ~    
        
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(?!admin), roles: ROLE_USER }

