security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: EntityBundle:User, property: user_username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:  ^/(?!admin)
            anonymous: ~
            form_login:
                login_path: /login2
                check_path: /login_check2
            context: main
            
        admin:
            pattern:  ^/admin
            anonymous: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            context: admin
        
            
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(?!admin), roles: ROLE_ADMIN }
